name: Unzip Portfolio
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip files
        run: |
          unzip -o "Khizra_Portfolio (2).zip"
          rm "Khizra_Portfolio (2).zip"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Unzipped portfolio files
